// <auto-generated />
namespace TravelMaker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addBlogCommentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBlogCommentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202304090954073_addBlogCommentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
